package tests 
{
	import laya.tools.SinaMData;
	import laya.utils.Handler;
	import stock.sinastock.DataTool;
	import stock.views.MDLine;
	/**
	 * ...
	 * @author ww
	 */
	public class TestSinaData 
	{
		
		public function TestSinaData() 
		{
			Laya.init(1000, 900);
			Laya.stage.bgColor = "#ffffff";
			//testData();
			//testData2();
			testData3();
		}
		private function testData():void
		{
			//https://hq.sinajs.cn/?list=ml_sh600012
			var hq_str_ml_sz300575="a+8AAHTvAACsJgAAme8AAIzwAACcGAAACPAAABjxAABUJAAAVfAAACjwAADYJwAAVfAAAILwAABcEgAAWfAAAEbwAACYIQAAWPAAAG7wAADQOQAAR/AAANjvAADcNwAAH/AAADzwAACMbgAALPAAAHjwAACkUQAATPAAAA7xAADAXQAAW/AAABjxAAC0LQAAZ/AAAA7xAAAEKQAAcPAAAPDwAAAYLgAAcvAAAObwAAB0DgAAefAAAATxAADsLAAAgPAAAATxAADkJQAAgvAAAKDwAACcGAAAgvAAAEbwAACoFgAAgfAAACjwAADkDAAAfvAAAPbvAADsEwAAe/AAACjwAAAMFwAAc/AAAOLvAAD8OgAAcfAAAOLvAABoEAAAavAAAPbvAACcMQAAY/AAAMTvAAA8QQAAYPAAAMTvAAA4GAAAX/AAAKDwAACMCgAAXvAAAEbwAABkGQAAXvAAAEbwAACUEQAAWfAAAFDwAADMWwAAWfAAADzwAAAgAwAAWPAAAM7vAABABgAAVvAAAM7vAAAkEwAAVvAAAOLvAAAsAQAAVfAAAPbvAABIDQAAVfAAAOLvAADQBwAAU/AAAMTvAACcGAAATPAAAIjvAADIMgAARPAAAAbvAADAKwAAOvAAAMDuAAB0JwAALvAAAPLuAABwMAAAJvAAAPLuAAC4JAAAJPAAABDvAAAcDAAAI/AAABrvAAAUBQAAIfAAADjvAABQFAAAIPAAAFbvAABsBwAAHPAAAC7vAAB4HgAAGvAAAPzuAAAQDgAAF/AAAOjuAAB0DgAAFvAAAAbvAAB4BQAAE/AAAELvAAC0FAAAEvAAALDvAACsDQAAEvAAABTwAACYCAAAEvAAADzwAACADAAAFPAAANLwAAAwEQAAFfAAAJbwAAA8DwAAFvAAAJbwAAAQDgAAF/AAAL7wAACsDQAAGPAAALDvAAD8CAAAGPAAAKDwAABYAgAAGPAAAKDwAAC8AgAAGfAAAKDwAAC4CwAAGfAAABTwAABkAAAAGfAAAMTvAADoAwAAGPAAAM7vAADwCgAAF/AAANjvAADUFwAAFvAAALDvAAC0FAAAFfAAAMTvAADIGQAAE/AAAHTvAAC0FAAAEvAAAC7vAAC4CwAAEfAAAKbvAADwCgAAEfAAADLwAADoAwAAEfAAADzwAAAUBQAAD/AAACjwAAA8KAAAD/AAACjwAADIAAAAD/AAAKbvAADcBQAADfAAAKbvAAAIIAAADfAAAKbvAADkDAAADfAAAKbvAABABgAACfAAAHTvAADkPgAABvAAAGrvAADoHAAABPAAAGDvAACQGgAABPAAAGDvAAAAAAAAA/AAAGrvAAB4BQAAA/AAALDvAADECQAAA/AAALrvAACQAQAAA/AAADzwAAA8DwAAA/AAAILwAAAQDgAABPAAADzwAAB0DgAABPAAAArwAABIDQAABPAAAArwAAAUBQAABPAAANjvAACYCAAABPAAANjvAACIEwAABPAAANjvAAC8AgAABPAAANjvAAAAAAAABPAAANjvAAAAAAAABPAAANjvAAAoCgAAA/AAAArwAAAUBQAABPAAAOLvAAAwEQAAA/AAANjvAAC8GwAAAPAAAC7vAADUMAAA/e8AAELvAADEIgAA+O8AABrvAAAAMgAA+O8AACTvAACEAwAA+O8AAFbvAABYAgAA+O8AACTvAABABgAA9+8AACTvAAAUBQAA9e8AAC7vAACoFgAA9e8AAMTvAAB9CwAA9e8AANjvAABIDQAA9e8AAArwAACQAQAA9e8AADLwAABMBAAA9e8AADLwAADcBQAA9e8AAHTvAADQBwAA9O8AAOLvAAAUBQAA9e8AAG7wAAArCgAA+O8AAFTxAACUKgAA++8AAATxAAAUHgAA/O8AANLwAABYAgAA/O8AAPDwAAC8AgAAAPAAADbxAACAJQAAAPAAAPDwAAD8CAAAAfAAAKrwAABMBAAAAfAAAKDwAAAIBwAAAvAAAKDwAABsBwAAAvAAAKDwAAC+CgAAA/AAAKDwAADECQAABPAAAPbvAADOGAAAA/AAAMTvAABAHwAAA/AAAArwAADwCgAAA/AAABTwAAD0AQAAA/AAAArwAAD0AQAAA/AAANjvAAA0CAAAA/AAAPbvAAAEEAAAA/AAANjvAABwFwAAA/AAAPbvAABYGwAAA/AAAPbvAAAAAAAAA/AAAM7vAAAsAQAAAvAAAM7vAAAwEQAAAvAAANjvAADoAwAAAvAAAOzvAAB4BQAAAvAAAMTvAACUEQAAAvAAAH7vAADoAwAAAfAAAGDvAAAYFQAA/+8AADjvAAC8GwAA/u8AAC7vAAD4EQAA/O8AABDvAADoHAAA+u8AABDvAADgFQAA+u8AAPzuAADECQAA9+8AALbuAAAIIAAA8e8AALbuAABMNgAA8O8AAKzuAABgCQAA7+8AAKzuAAAIBwAA6O8AAEjuAACMPAAA3+8AAIDtAABMNgAA1O8AACbtAACENQAAzO8AAAjtAADkJQAAxO8AAEjuAAAkLAAAwO8AAD7uAADwIwAAv+8AAPzuAABAHwAAve8AAO7tAAA8DwAAve8AAPjtAAAgAwAAve8AAKzuAADoAwAAtu8AANTuAAB0QAAAtu8AAN7uAAAkRQAAtu8AAKDwAACMIwAAu+8AANjvAAA4SgAAwe8AABjxAADsRQAAwu8AAADwAABwFwAAx+8AANjvAAAYRwAAx+8AAPrwAABAHwAAye8AALrvAAAEKQAAye8AAMTvAAA0CAAAy+8AAHjwAADkJQAAzO8AALTwAACcGAAAzu8AAEbwAAC8GwAAzu8AAM7vAADkDAAAz+8AAKDwAAA4GAAAzu8AABTwAADAEgAAzu8AAGrvAABYAgAAzu8AAH7vAACkBgAAzu8AAH7vAAAAAAAA0O8AAIzwAADkJQAA0+8AALTwAABQRgAA1e8AAKDwAAAoIwAA1e8AAIzwAAD0AQAA1e8AAIjvAABMBAAA1e8AAKbvAAAgAwAA1e8AAH7vAADoAwAA1O8AAFbvAAAEEAAA1O8AALDvAAB0DgAA1O8AAFbvAADwCgAA0+8AABDvAAAkEwAA0u8AAEjuAACIEwAA0e8AAI7uAABIDQAA0e8AAJjuAACQAQAA0O8AAKzuAAAoCgAA0O8AAKLuAAAIBwAAzu8AAKzuAAAEEAAAze8AAKzuAAAkEwAAzO8AAAbvAACoFgAAzO8AAPzuAABgCQAAy+8AABDvAADYDgAAyu8AAELvAAC0FAAAyu8AADzwAAB4BQAAyu8AANjvAADIAAAAyu8AANjvAAAAAAAAyu8AANjvAAAAAAAAyu8AABrvAAB4BQAAyu8AACTvAAAoCgAAyu8AAMTvAAAoCgAAyu8AADzwAADoHAAAy+8AAIzwAACsDQAAze8AADzwAADkJQAAzu8AAPrwAACoFgAA0O8AAJbwAADcHgAA0e8AAJbwAACkHwAA0e8AADzwAADYDgAA0u8AAEzvAAAYFQAA0O8AAELvAAAgNQAAz+8AAPzuAAC4JAAAzu8AAPLuAACQGgAAze8AAKbvAAAkEwAAzO8AAMruAABcRAAAyO8AAEjuAABwMAAAwu8AAE7tAACENQAAve8AAOTtAAB8LgAAue8AAOTtAAD8OgAAtu8AAHbtAABMHQAAq+8AABztAACsWAAApu8AACbtAAAEKQAAoe8AAJTtAABAOAAAnu8AAJ7tAABMHQAAmu8AAGLtAABQLQAAlu8AAGztAABoKQAAjO8AAKTsAADwVQAAd+8AAGDqAAAMewAAd+8AAGDqAAD0AQAAd+8AAGDqAAAAAAAAd+8AAGDqAAAAAAAAWe8AAGrqAACMhwAA////////////////";

			var dataArr:Array;
			dataArr = DataTool.db(hq_str_ml_sz300575);
			trace(dataArr);
			var dataL:Array;
			dataL = DataTool.fB(dataArr);
			trace(dataL);
		}
		private function testData2():void
		{
			var MDData:SinaMData;
			MDData = new SinaMData();
			MDData.completeHandler = new Handler(this, onStockCP);
			MDData.getData("600012");
			
		}
		private function onStockCP(data:*):void
		{
			trace("stockData:",data);
		}
		private function testData3():void
		{
			var mdLine:MDLine;
			mdLine = new MDLine();
			mdLine.setStock("000912");
			mdLine.lineHeight = 400;
			mdLine.lineWidth = 850;
			mdLine.pos(10, 400);
			mdLine.setUpGrids();
			mdLine.addStock("002795");
			mdLine.addStock("002349");
			mdLine.addStock("600282");
			mdLine.addStock("300076");
			mdLine.addStock("sh000001");
			mdLine.addStock("sz399001");
			
			Laya.stage.addChild(mdLine);
			mdLine.startFresh();
		}
	}

}